name = "llama-unsloth"
description = "Meta Llama 3.1 8B Instruct (unsloth 4bit)"
model_id = "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"
quantization = "bitsandbytes"
load_format = "bitsandbytes"
max_model_len = 6000
gpu_memory_utilization = 0.99
enforce_eager = false
trust_remote_code = false

[additional_params]
